nelmio_api_doc:
    documentation:
        info:
            title: Symfony6.4-MariaDb-OrderAPI
            description: damiancloud
            version: 1.0.0
    areas:
        default:
            path_patterns:
                - ^/api(?!/_profiler)
                - ^/api(?!/_debug)
                - ^/orders
