version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: image-php_to_pgsql
    container_name: php-symfony-app
    restart: always
    working_dir: /var/www
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./:/var/www
    depends_on:
      - mariadb-service
  nginx:
    image: nginx:1.19-alpine
    container_name: php-symfony-app-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d
  mariadb-service:
    image: mariadb:latest
    container_name: php-symfony-app-mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: damiancloud85
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes: 
      - ./db:/var/lib/mysql
